version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    versioning-strategy: increase
    open-pull-requests-limit: 20
    groups:
      next-js:
        patterns:
          - 'next'
          - '@next/eslint-plugin-next'
      turbo:
        patterns:
          - 'turbo'
          - 'eslint-config-turbo'
